# Generated by Django 6.0.3 on 2026-03-28 06:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('worker_to_contractor', 'Worker rates Contractor'), ('contractor_to_worker', 'Contractor rates Worker')], max_length=30)),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('note', models.CharField(blank=True, max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='jobs.jobengagement')),
                ('ratee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL)),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ratings_rating',
                'ordering': ['-created_at'],
                'unique_together': {('engagement', 'direction')},
            },
        ),
        migrations.CreateModel(
            name='SkillEndorsement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('reads_plans', 'Can read technical drawings'), ('tiling_quality', 'Tiling finish quality is high'), ('punctual', 'Reliable timekeeping'), ('plastering', 'Plastering finish is smooth'), ('clean_work', 'Keeps worksite clean'), ('team_player', 'Works well in a team'), ('electrical_safe', 'Follows electrical safety'), ('plumbing_neat', 'Plumbing work is neat'), ('fast_worker', 'Works quickly without errors'), ('tools_care', 'Takes care of tools and materials')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contractor', models.ForeignKey(limit_choices_to={'role': 'contractor'}, on_delete=django.db.models.deletion.CASCADE, related_name='endorsements_given', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsements', to='jobs.jobengagement')),
                ('worker', models.ForeignKey(limit_choices_to={'role': 'worker'}, on_delete=django.db.models.deletion.CASCADE, related_name='endorsements_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ratings_endorsement',
                'ordering': ['-created_at'],
                'unique_together': {('engagement', 'tag')},
            },
        ),
    ]
