# Generated by Django 5.0.6 on 2026-03-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='location_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='primary_skill',
            field=models.CharField(blank=True, choices=[('mason', 'Mason'), ('electrician', 'Electrician'), ('painter', 'Painter'), ('labourer', 'Labourer')], max_length=30, null=True),
        ),
    ]
