# Generated by Django 5.2.12 on 2026-03-28 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContractorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("location", models.CharField(max_length=120)),
                ("phone_number", models.CharField(max_length=20, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="WorkerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("location", models.CharField(max_length=120)),
                ("phone_number", models.CharField(max_length=20, unique=True)),
                (
                    "primary_skill",
                    models.CharField(
                        choices=[
                            ("Mason", "Mason"),
                            ("Electrician", "Electrician"),
                            ("Painter", "Painter"),
                            ("Labourer", "Labourer"),
                            ("Tiler", "Tiler"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "skill_required",
                    models.CharField(
                        choices=[
                            ("Mason", "Mason"),
                            ("Electrician", "Electrician"),
                            ("Painter", "Painter"),
                            ("Labourer", "Labourer"),
                            ("Tiler", "Tiler"),
                        ],
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(max_length=120)),
                ("duration_days", models.PositiveIntegerField(default=1)),
                ("daily_rate", models.PositiveIntegerField()),
                ("workers_needed", models.PositiveIntegerField(default=1)),
                ("radius_km", models.PositiveIntegerField(default=10)),
                ("urgent_same_day", models.BooleanField(default=False)),
                ("start_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("CLOSED", "Closed")],
                        default="OPEN",
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contractor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="core.contractorprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobEngagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_on", models.DateField()),
                ("contractor_rating_for_worker", models.PositiveSmallIntegerField()),
                ("worker_rating_for_contractor", models.PositiveSmallIntegerField()),
                ("note_for_worker", models.CharField(blank=True, max_length=180)),
                ("note_for_contractor", models.CharField(blank=True, max_length=180)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contractor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_ratings",
                        to="core.contractorprofile",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagements",
                        to="core.jobposting",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagements",
                        to="core.workerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SkillEndorsement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_tag", models.CharField(max_length=80)),
                ("note", models.CharField(blank=True, max_length=180)),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endorsements",
                        to="core.jobengagement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("APPLIED", "Applied"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="APPLIED",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="core.jobposting",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="core.workerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FavoriteWorker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contractor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="core.contractorprofile",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favored_by",
                        to="core.workerprofile",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="jobengagement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("contractor_rating_for_worker__gte", 1),
                    ("contractor_rating_for_worker__lte", 5),
                ),
                name="contractor_rating_worker_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="jobengagement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("worker_rating_for_contractor__gte", 1),
                    ("worker_rating_for_contractor__lte", 5),
                ),
                name="worker_rating_contractor_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="jobengagement",
            constraint=models.UniqueConstraint(
                fields=("job", "worker"), name="unique_engagement_per_job_worker"
            ),
        ),
        migrations.AddConstraint(
            model_name="jobapplication",
            constraint=models.UniqueConstraint(
                fields=("job", "worker"), name="unique_worker_application_per_job"
            ),
        ),
        migrations.AddConstraint(
            model_name="favoriteworker",
            constraint=models.UniqueConstraint(
                fields=("contractor", "worker"),
                name="unique_contractor_favorite_worker",
            ),
        ),
    ]
