# Generated by Django 6.0.3 on 2026-03-28 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_category', models.CharField(blank=True, choices=[('mason', 'Mason / Mistri'), ('electrician', 'Electrician'), ('plumber', 'Plumber'), ('painter', 'Painter'), ('carpenter', 'Carpenter'), ('labourer', 'General Labourer'), ('welder', 'Welder'), ('tiler', 'Tiler'), ('fabricator', 'Fabricator'), ('rebar', 'Rebar Worker')], max_length=30)),
                ('secondary_skills', models.JSONField(blank=True, default=list)),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('preferred_radius_km', models.PositiveIntegerField(default=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workers_profile',
            },
        ),
        migrations.CreateModel(
            name='FavouriteWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('contractor', models.ForeignKey(limit_choices_to={'role': 'contractor'}, on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(limit_choices_to={'role': 'worker'}, on_delete=django.db.models.deletion.CASCADE, related_name='favourited_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workers_favourite',
                'unique_together': {('contractor', 'worker')},
            },
        ),
    ]
