# Generated by Django 6.0.3 on 2026-03-28 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('otp', 'OTP'), ('job_alert', 'Job Alert'), ('hired', 'Hired'), ('rating_reminder', 'Rating Reminder'), ('urgent_broadcast', 'Urgent Broadcast')], max_length=30)),
                ('message', models.TextField()),
                ('sent_via', models.CharField(default='sms', max_length=20)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
